"""Google Docs Tool — creates a formatted trip itinerary document."""
from googleapiclient.discovery import build
from google.oauth2.credentials import Credentials
from langchain_core.tools import tool
import json


def _get_docs_service(token: dict):
    creds = Credentials(
        token=token["access_token"],
        refresh_token=token.get("refresh_token"),
        token_uri="https://oauth2.googleapis.com/token",
        client_id=token.get("client_id"),
        client_secret=token.get("client_secret"),
    )
    return build("docs", "v1", credentials=creds)


def _get_drive_service(token: dict):
    creds = Credentials(
        token=token["access_token"],
        refresh_token=token.get("refresh_token"),
        token_uri="https://oauth2.googleapis.com/token",
        client_id=token.get("client_id"),
        client_secret=token.get("client_secret"),
    )
    return build("drive", "v3", credentials=creds)


@tool
def create_trip_document(
    google_token_json: str,
    destination: str,
    origin: str,
    departure_date: str,
    return_date: str,
    adults: int,
    flights: str,
    preferences: str = "",
) -> dict:
    """Create a Google Docs trip itinerary document.
    Only call this after explicit user confirmation.

    Args:
        google_token_json: JSON string of the user's Google OAuth token
        destination: Trip destination city/country
        origin: Trip origin city/country
        departure_date: Departure date string
        return_date: Return date string
        adults: Number of travelers
        flights: JSON string of flight options from Amadeus
        preferences: User's travel preferences
    Returns doc URL and ID on success.
    """
    try:
        token = json.loads(google_token_json)
        docs = _get_docs_service(token)
        drive = _get_drive_service(token)

        title = f"✈️ NaviGO Trip: {origin} → {destination} ({departure_date})"
        doc = docs.documents().create(body={"title": title}).execute()
        doc_id = doc["documentId"]

        # Parse flights for display
        try:
            flight_list = json.loads(flights) if flights else []
        except Exception:
            flight_list = []

        flight_text = ""
        for i, f in enumerate(flight_list, 1):
            legs = f.get("legs", [{}])
            leg = legs[0]
            flight_text += (
                f"Option {i}: {f.get('airline_code', '?')} | "
                f"{f.get('price', '?')} | "
                f"Duration: {leg.get('duration', '?')} | "
                f"Stops: {leg.get('stops', '?')}\n"
            )

        body_text = (
            f"🌍 TRIP ITINERARY\n"
            f"Generated by NaviGO AI Travel Agent\n\n"
            f"TRIP DETAILS\n"
            f"• Origin: {origin}\n"
            f"• Destination: {destination}\n"
            f"• Departure: {departure_date}\n"
            f"• Return: {return_date}\n"
            f"• Travelers: {adults} adult(s)\n"
            f"• Preferences: {preferences or 'None specified'}\n\n"
            f"FLIGHT OPTIONS\n"
            f"{flight_text or 'No flight data available'}\n\n"
            f"SUGGESTED ITINERARY\n"
            f"• Day 1: Arrive in {destination}, check in & explore\n"
            f"• Day 2-N: Explore local attractions\n"
            f"• Last Day: Return flight from {destination}\n\n"
            f"TIPS\n"
            f"• Book accommodation in advance\n"
            f"• Check visa requirements for your passport\n"
            f"• Travel insurance is recommended\n"
        )

        requests = [{
            "insertText": {
                "location": {"index": 1},
                "text": body_text,
            }
        }]
        docs.documents().batchUpdate(
            documentId=doc_id,
            body={"requests": requests},
        ).execute()

        # Make shareable
        drive.permissions().create(
            fileId=doc_id,
            body={"type": "anyone", "role": "reader"},
        ).execute()

        doc_url = f"https://docs.google.com/document/d/{doc_id}/edit"
        return {"success": True, "doc_url": doc_url, "doc_id": doc_id, "title": title}

    except Exception as e:
        return {"error": f"Failed to create document: {str(e)}"}
